/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;

/**
 *
 * @author nardi
 */
public class Interfaccia extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaccia.class.getName());

    /**
     * Creates new form Interfaccia
     */
    public Interfaccia() {
        initComponents();
    }
private Staffetta c1, c2, c3, c4;

private void avviaGara() {
    // 1. Reset preventivo
    resetGara();

    // 2. Calcolo velocità dallo sleep
    int sleep = 50; 
    String sel = Progres.getSelectedItem().toString();
    if(sel.equals("Lento")) sleep = 150;
    if(sel.equals("Veloce")) sleep = 20;

    // 3. Inizializzazione Thread
    c1 = new Staffetta(1, sleep);
    c2 = new Staffetta(2, sleep);
    c3 = new Staffetta(3, sleep);
    c4 = new Staffetta(4, sleep);

    // 4. Definizione dell'Observer (cosa succede quando il thread avanza)
    Staffetta.Corridore observer = (n, valore) -> {
        java.awt.EventQueue.invokeLater(() -> {
            switch (n) {
                case 1 -> { jProgressBar1.setValue(valore); jLabel8.setText(String.valueOf(valore)); }
                case 2 -> { jProgressBar2.setValue(valore); jLabel5.setText(String.valueOf(valore)); }
                case 3 -> { jProgressBar3.setValue(valore); jLabel6.setText(String.valueOf(valore)); }
                case 4 -> { jProgressBar4.setValue(valore); jLabel7.setText(String.valueOf(valore)); }
            }
        });
    };

    // Aggiungi observer a tutti
    c1.addCorridore(observer); c2.addCorridore(observer);
    c3.addCorridore(observer); c4.addCorridore(observer);

    // 5. Concatenazione (il testimone)
    c1.setSuccessivo(c2);
    c2.setSuccessivo(c3);
    c3.setSuccessivo(c4);

    // 6. Start e sblocco del primo
    c1.start(); c2.start(); c3.start(); c4.start();
    c1.sblocca();
}
private void resetGara() {
    if (c1 != null) { c1.ferma(); c2.ferma(); c3.ferma(); c4.ferma(); }
    jProgressBar2.setValue(0); jProgressBar3.setValue(0);
    jProgressBar1.setValue(0); jProgressBar4.setValue(0);
    jLabel5.setText("0"); jLabel6.setText("0"); jLabel7.setText("0"); jLabel8.setText("0");
}

private void setPausaTutti(boolean pausa) {
    if (c1 != null) {
        c1.setPausa(pausa); c2.setPausa(pausa);
        c3.setPausa(pausa); c4.setPausa(pausa);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Avvia = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Pausa = new javax.swing.JButton();
        Riprendi = new javax.swing.JButton();
        Progres = new javax.swing.JComboBox<>();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Avvia.setText("Avvia");
        Avvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvviaActionPerformed(evt);
            }
        });
        getContentPane().add(Avvia, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 298, -1, -1));

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 298, -1, -1));

        Pausa.setText("Pausa");
        Pausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PausaActionPerformed(evt);
            }
        });
        getContentPane().add(Pausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 298, -1, -1));

        Riprendi.setText("Riprendi");
        Riprendi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiprendiActionPerformed(evt);
            }
        });
        getContentPane().add(Riprendi, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 298, -1, -1));

        Progres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normale", "Lento", "Veloce" }));
        getContentPane().add(Progres, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 298, -1, -1));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 61, 504, 28));
        getContentPane().add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 107, 504, 28));
        getContentPane().add(jProgressBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 155, 504, 28));
        getContentPane().add(jProgressBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 199, 504, 28));

        jLabel5.setText("0");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 109, 95, 28));

        jLabel6.setText("0");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 95, 38));

        jLabel7.setText("0");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 95, 30));

        jLabel8.setText("0");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 61, 95, 28));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvviaActionPerformed
avviaGara();        // TODO add your handling code here:
    }//GEN-LAST:event_AvviaActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
resetGara();        // TODO add your handling code here:
    }//GEN-LAST:event_ResetActionPerformed

    private void PausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PausaActionPerformed
setPausaTutti(true);        // TODO add your handling code here:
    }//GEN-LAST:event_PausaActionPerformed

    private void RiprendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiprendiActionPerformed
setPausaTutti(false);        // TODO add your handling code here:
    }//GEN-LAST:event_RiprendiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaccia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Avvia;
    private javax.swing.JButton Pausa;
    private javax.swing.JComboBox<String> Progres;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Riprendi;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    // End of variables declaration//GEN-END:variables
}
